[project]
name = "bird_watcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.0.0",
    "gpiozero>=2.0.1.post2; sys_platform == 'linux'",
    "inference>=1.2.0",
    "opencv-python>=4.10.0.84",
    "rfdetr>=1.6.2",
    "supervision>=0.27.0.post2",
]

[tool.pytest.ini_options]
pythonpath = ["."]

